blank_issues_enabled: true
contact_links:
  - name: Rose Discord
    url: https://discord.com/invite/roseskins
    about: Get installation help, ask general questions, and talk with the Rose community.
